[general]
import = [
	"~/.config/alacritty/themes/themes/alabaster_dark.toml"
]

[window]

padding = {x = 15, y = 10}
opacity = 1


[font]

normal = {family = "CozetteVector", style = "normal"}

size = 15

[colors]

[colors.primary]
background = "#010101"
foreground = "#FFFFFF"
